Repository vr-tower-defense/vr-tower-defense, pull requests merged in 2019-04, with the labels that each got.

#18 #9 Create LSD Scene with VR Player
  src/Assets/Scenes/LSDScene.unity
  src/Assets/Scenes/LSDScene.unity.meta
  src/Assets/SteamVR_Input.meta
  src/Assets/SteamVR_Input/ActionSetClasses.meta
  src/ProjectSettings/QualitySettings.asset
  src/ProjectSettings/UnityConnectSettings.asset
  src/unityProject.vrmanifest
Labels: feature

#19 Add project folder structure
  src/Assets/LightSkyDefense.meta
  src/Assets/LightSkyDefense/.gitkeep
  src/Assets/LightSkyDefense/Materials.meta
  src/Assets/LightSkyDefense/Materials/.gitkeep
  src/Assets/LightSkyDefense/Models.meta
  src/Assets/LightSkyDefense/Models/.gitkeep
  src/Assets/LightSkyDefense/Prefabs.meta
  src/Assets/LightSkyDefense/Prefabs/.gitkeep
  src/Assets/LightSkyDefense/Resources.meta
  src/Assets/LightSkyDefense/Resources/.gitkeep
  src/Assets/LightSkyDefense/Resources/Audio.meta
  src/Assets/LightSkyDefense/Resources/Audio/.gitkeep
  src/Assets/LightSkyDefense/Resources/Shaders.meta
  src/Assets/LightSkyDefense/Resources/Shaders/.gitkeep
  src/Assets/LightSkyDefense/Resources/Texture.meta
  src/Assets/LightSkyDefense/Resources/Texture/.gitkeep
  src/Assets/LightSkyDefense/Scenes.meta
  src/Assets/LightSkyDefense/Scenes/.gitkeep
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity.meta
  src/Assets/LightSkyDefense/Scenes/SampleScene.unity
  src/Assets/LightSkyDefense/Scenes/SampleScene.unity.meta
  src/Assets/LightSkyDefense/Scripts.meta
  src/Assets/LightSkyDefense/Scripts/.gitkeep
Labels: task

#27 Create Azure build pipeline
  azure-pipelines.yml
  src/ProjectSettings/EditorBuildSettings.asset
  src/ProjectSettings/GraphicsSettings.asset
  src/ProjectSettings/ProjectSettings.asset
Labels: task

#25 Feature/#12 inflict damage on enemy with tower
  src/Assets/LightSkyDefense/Prefabs/Enemy_1.prefab
  src/Assets/LightSkyDefense/Prefabs/StandardBullet.prefab
  src/Assets/LightSkyDefense/Prefabs/Tower.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/DestroyBullet.cs
  src/ProjectSettings/TagManager.asset
Labels: feature

#28 Feature/#16 collect resource acceptation criteria
  src/Assets/LightSkyDefense/Scripts/Credit.cs
Labels: feature

#37 Feature/#10 create dial control
  src/Assets/LightSkyDefense/Controls.meta
  src/Assets/LightSkyDefense/Controls/Dial.meta
  src/Assets/LightSkyDefense/Controls/Dial/Dial.cs
  src/Assets/LightSkyDefense/Controls/Dial/Dial.cs.meta
  src/Assets/LightSkyDefense/Controls/Dial/DialOption.cs
  src/Assets/LightSkyDefense/Controls/Dial/DialOption.cs.meta
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOption.cs
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOption.cs.meta
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleOne.prefab
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleOne.prefab.meta
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleOneColor.mat
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleOneColor.mat.meta
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleTwo.prefab
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleTwo.prefab.meta
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleTwoColor.mat
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleTwoColor.mat.meta
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/SteamVR_Input.meta
  src/Assets/SteamVR_Input/ActionSetClasses.meta
  src/Assets/SteamVR_Input/ActionSetClasses/SteamVR_Input_ActionSet_buggy.cs
  src/Assets/SteamVR_Input/ActionSetClasses/SteamVR_Input_ActionSet_buggy.cs.meta
  src/Assets/SteamVR_Input/ActionSetClasses/SteamVR_Input_ActionSet_default.cs
  src/Assets/SteamVR_Input/ActionSetClasses/SteamVR_Input_ActionSet_default.cs.meta
  src/Assets/SteamVR_Input/ActionSetClasses/SteamVR_Input_ActionSet_mixedreality.cs
  src/Assets/SteamVR_Input/ActionSetClasses/SteamVR_Input_ActionSet_mixedreality.cs.meta
  src/Assets/SteamVR_Input/ActionSetClasses/SteamVR_Input_ActionSet_platformer.cs
  src/Assets/SteamVR_Input/ActionSetClasses/SteamVR_Input_ActionSet_platformer.cs.meta
  src/Assets/SteamVR_Input/SteamVR_Actions.asmdef
  src/Assets/SteamVR_Input/SteamVR_Actions.asmdef.meta
  src/Assets/SteamVR_Input/SteamVR_Input_ActionSets.cs
  src/Assets/SteamVR_Input/SteamVR_Input_ActionSets.cs.meta
  src/Assets/SteamVR_Input/SteamVR_Input_Actions.cs
  src/Assets/SteamVR_Input/SteamVR_Input_Actions.cs.meta
  src/Assets/SteamVR_Input/SteamVR_Input_Initialization.cs
  src/Assets/SteamVR_Input/SteamVR_Input_Initialization.cs.meta
  src/ProjectSettings/QualitySettings.asset
  src/ProjectSettings/TimeManager.asset
  src/actions.json
  src/bindings_holographic_controller.json
  src/bindings_knuckles.json
  src/bindings_oculus_touch.json
  src/bindings_vive_controller.json
Labels: feature

#41 #7 Create Explode Method in enemy script. Add explode particle system …
  src/Assets/LightSkyDefense/Materials/ExplosionMat.mat
  src/Assets/LightSkyDefense/Materials/ExplosionMat.mat.meta
  src/Assets/LightSkyDefense/Prefabs/Enemy_1.prefab
  src/Assets/LightSkyDefense/Resources/Effects.meta
  src/Assets/LightSkyDefense/Resources/Effects/.gitkeep
  src/Assets/LightSkyDefense/Resources/Effects/ExplosionParticleSystem.prefab
  src/Assets/LightSkyDefense/Resources/Effects/ExplosionParticleSystem.prefab.meta
  src/Assets/LightSkyDefense/Scripts/Enemy.cs
  src/Assets/LightSkyDefense/Scripts/GameManager.cs
  src/Assets/LightSkyDefense/Scripts/GameManager.cs.meta
Labels: feature

#44 Feature/#4 visualize the path
  src/Assets/LightSkyDefense/Editor.meta
  src/Assets/LightSkyDefense/Editor/PathInspector.cs
  src/Assets/LightSkyDefense/Editor/PathInspector.cs.meta
  src/Assets/LightSkyDefense/Prefabs/LineRendererPrefab.prefab
  src/Assets/LightSkyDefense/Prefabs/LineRendererPrefab.prefab.meta
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Curve.cs
  src/Assets/LightSkyDefense/Scripts/Curve.cs.meta
  src/Assets/LightSkyDefense/Scripts/Path.cs
  src/Assets/LightSkyDefense/Scripts/Path.cs.meta
Labels: feature

#46 Feature/#10 dial option preview
  src/Assets/LightSkyDefense/Controls/Dial/Dial.cs
  src/Assets/LightSkyDefense/Controls/Dial/DialOption.cs
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOption.cs
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleOne.prefab
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleOne.prefab.meta
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleTwo.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/ProjectSettings/ProjectSettings.asset
Labels: feature

#53 #51 Sound effect, deletion on trigger hold.
  src/Assets/LightSkyDefense/Prefabs/Tower.prefab
  src/Assets/LightSkyDefense/Resources/Audio/credit.wav
  src/Assets/LightSkyDefense/Resources/Audio/credit.wav.meta
  src/Assets/LightSkyDefense/Resources/Audio/explosion.wav
  src/Assets/LightSkyDefense/Resources/Audio/explosion.wav.meta
  src/Assets/LightSkyDefense/Scripts/Deletable.cs
  src/Assets/LightSkyDefense/Scripts/Deletable.cs.meta
Labels: feature

#45 Feature/#40 rotate towers towards enemies they shoot at
  src/Assets/LightSkyDefense/Prefabs/Tower.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/TowerBehaviour.cs
  src/ProjectSettings/ProjectSettings.asset
Labels: feature

#56 Feature/#55 make a fast shooting tower
  src/Assets/LightSkyDefense/Materials/CreditMaterial.mat
  src/Assets/LightSkyDefense/Materials/CreditMaterial.mat.meta
  src/Assets/LightSkyDefense/Materials/FastBulletLowDamageLowIntervalTowerMaterial.mat
  src/Assets/LightSkyDefense/Materials/FastBulletLowDamageLowIntervalTowerMaterial.mat.meta
  src/Assets/LightSkyDefense/Materials/FastSpeedLowDamageBulletMaterial.mat
  src/Assets/LightSkyDefense/Materials/FastSpeedLowDamageBulletMaterial.mat.meta
  src/Assets/LightSkyDefense/Materials/SlowBulletHighDamageHighIntervalTowerMaterial.mat
  src/Assets/LightSkyDefense/Materials/SlowBulletHighDamageHighIntervalTowerMaterial.mat.meta
  src/Assets/LightSkyDefense/Materials/SlowSpeedHighDamageBulletMaterial.mat
  src/Assets/LightSkyDefense/Materials/SlowSpeedHighDamageBulletMaterial.mat.meta
  src/Assets/LightSkyDefense/Prefabs/FastBulletLowDamageLowIntervalTower.prefab
  src/Assets/LightSkyDefense/Prefabs/FastBulletLowDamageLowIntervalTower.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/FastSpeedLowDamageBullet.prefab
  src/Assets/LightSkyDefense/Prefabs/FastSpeedLowDamageBullet.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/SlowBulletHighDamageHighIntervalTower.prefab
  src/Assets/LightSkyDefense/Prefabs/SlowBulletHighDamageHighIntervalTower.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/SlowSpeedHighDamageBullet.prefab
  src/Assets/LightSkyDefense/Prefabs/SlowSpeedHighDamageBullet.prefab.meta
  src/Assets/LightSkyDefense/Resources/Audio/Canon1.wav
  src/Assets/LightSkyDefense/Resources/Audio/Canon1.wav.meta
  src/Assets/LightSkyDefense/Resources/Audio/QuickShotSound.wav
  src/Assets/LightSkyDefense/Resources/Audio/QuickShotSound.wav.meta
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/ProjectSettings/ProjectSettings.asset
Labels: feature

#65 #64 Clear target when not in range
  src/Assets/LightSkyDefense/Scripts/TowerBehaviour.cs
Labels: bug

#67 #42 Rename assets to convention
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleOneColorMat.mat
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleOneColorMat.mat.meta
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleTwoColorMat.mat
  src/Assets/LightSkyDefense/Controls/Dial/SpawnDialOptionExampleTwoColorMat.mat.meta
  src/Assets/LightSkyDefense/Materials/CreditMat.mat
  src/Assets/LightSkyDefense/Materials/CreditMat.mat.meta
  src/Assets/LightSkyDefense/Materials/FastBulletLowDamageLowIntervalTowerMat.mat
  src/Assets/LightSkyDefense/Materials/FastBulletLowDamageLowIntervalTowerMat.mat.meta
  src/Assets/LightSkyDefense/Materials/FastSpeedLowDamageBulletMat.mat
  src/Assets/LightSkyDefense/Materials/FastSpeedLowDamageBulletMat.mat.meta
  src/Assets/LightSkyDefense/Materials/SkyboxMat.mat
  src/Assets/LightSkyDefense/Materials/SkyboxMat.mat.meta
  src/Assets/LightSkyDefense/Materials/SlowBulletHighDamageHighIntervalTowerMat.mat
  src/Assets/LightSkyDefense/Materials/SlowBulletHighDamageHighIntervalTowerMat.mat.meta
  src/Assets/LightSkyDefense/Materials/SlowSpeedHighDamageBulletMat.mat
  src/Assets/LightSkyDefense/Materials/SlowSpeedHighDamageBulletMat.mat.meta
  src/Assets/LightSkyDefense/Models/Enemy_1.png
  src/Assets/LightSkyDefense/Models/Enemy_1.png.meta
  src/Assets/LightSkyDefense/Models/Materials/Enemy_1_Mat.mat
  src/Assets/LightSkyDefense/Models/Materials/Enemy_1_Mat.mat.meta
Labels: task

#71 Add target prediction for projectile #70
  src/Assets/LightSkyDefense/Prefabs/FastBulletLowDamageLowIntervalTower.prefab
  src/Assets/LightSkyDefense/Prefabs/SlowBulletHighDamageHighIntervalTower.prefab
  src/Assets/LightSkyDefense/Scripts/TowerBehaviour.cs
Labels: feature
