Repository vr-tower-defense/vr-tower-defense, pull requests merged in 2019-05, with the labels that each got.

#92 CreditOwner turned into PlayerStats #87
  src/Assets/LightSkyDefense/Scripts/Credit.cs
  src/Assets/LightSkyDefense/Scripts/CreditOwner.cs
  src/Assets/LightSkyDefense/Scripts/PlayerStats.cs
  src/Assets/LightSkyDefense/Scripts/PlayerStats.cs.meta
  src/Assets/LightSkyDefense/Scripts/TowerBehaviour.cs
Labels: feature

#93 Enemy damages player #88
  src/Assets/LightSkyDefense/Scripts/Enemy.cs
Labels: feature

#91 Feature/#83 Refactor path system
  src/Assets/LightSkyDefense/Scripts/Enemy.cs
  src/Assets/LightSkyDefense/Scripts/GameManager.cs
  src/Assets/LightSkyDefense/Scripts/Path.cs
Labels: feature

#98 Feature/#97 add game end event
  src/Assets/LightSkyDefense/Scripts/OnGameEndTarget.cs
  src/Assets/LightSkyDefense/Scripts/OnGameEndTarget.cs.meta
Labels: feature

#99 Game freezes + Grey after effect on loss
  src/Assets/LightSkyDefense/Resources/Shaders/DefeatShader.shader
  src/Assets/LightSkyDefense/Resources/Shaders/DefeatShader.shader.meta
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Enemy.cs
  src/Assets/LightSkyDefense/Scripts/GameManager.cs
  src/Assets/LightSkyDefense/Scripts/GreyscaleAfterEffect.cs
  src/Assets/LightSkyDefense/Scripts/GreyscaleAfterEffect.cs.meta
  src/Assets/LightSkyDefense/Scripts/PlayerStats.cs
  src/Assets/LightSkyDefense/Scripts/TowerBehaviour.cs
Labels: feature

#106 removed shadow
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
Labels: bug

#110 Feature/#109 layer based collision detection
  artwork/models/bullet/Speedbullet.blend
  artwork/models/bullet/Speedbullet.fbx
  artwork/models/missile/missile.blend
  artwork/models/missile_launcher/missile_launcher.blend
  artwork/models/missile_launcher/missile_launcher.fbx
  artwork/models/missile_launcher/missile_launcher_diffuse_color.png
  artwork/models/scoreboard/Scoreboard.blend
  artwork/models/scoreboard/Scoreboard.fbx
  artwork/models/turret/turret.blend
  artwork/models/turret/turret.fbx
  assets/models/missile_launcher.blend
  src/Assets/LightSkyDefense/Models/Enemy.meta
  src/Assets/LightSkyDefense/Models/Enemy/Enemy.fbx
  src/Assets/LightSkyDefense/Models/Enemy/Enemy.fbx.meta
  src/Assets/LightSkyDefense/Models/Enemy/EnemyMaterial.mat
  src/Assets/LightSkyDefense/Models/Enemy/EnemyMaterial.mat.meta
  src/Assets/LightSkyDefense/Models/Missile.fbx
  src/Assets/LightSkyDefense/Models/Missile.fbx.meta
  src/Assets/LightSkyDefense/Models/MissileLauncher.meta
  src/Assets/LightSkyDefense/Models/MissileLauncher/MissileLauncherMaterial.mat
  src/Assets/LightSkyDefense/Models/MissileLauncher/MissileLauncherMaterial.mat.meta
  src/Assets/LightSkyDefense/Models/MissileLauncher/missile_launcher.fbx
  src/Assets/LightSkyDefense/Models/MissileLauncher/missile_launcher.fbx.meta
  src/Assets/LightSkyDefense/Models/MissileLauncher/missile_launcher_diffuse_color.png
  src/Assets/LightSkyDefense/Models/MissileLauncher/missile_launcher_diffuse_color.png.meta
  src/Assets/LightSkyDefense/Models/SlowBullet.fbx
  src/Assets/LightSkyDefense/Prefabs/Enemies.meta
  src/Assets/LightSkyDefense/Prefabs/Pickups/Credit.prefab
  src/Assets/LightSkyDefense/Prefabs/Projectiles/FastSpeedLowDamageBullet.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/Missile.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/Missile.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncher.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncher.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncherDialOption.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncherDialOption.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/SlowBulletHighDamageHighIntervalTower.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Turret.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/Turret/Bullet.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Turret/Bullet.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/Turret/Turret.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Turret/Turret.prefab.meta
  src/Assets/LightSkyDefense/Resources/Prefabs/Enemy.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/BulletBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/BulletBehaviour.cs.meta
  src/Assets/LightSkyDefense/Scripts/Enemy.cs
  src/Assets/LightSkyDefense/Scripts/TowerBehaviour.cs
  src/ProjectSettings/DynamicsManager.asset
  src/ProjectSettings/TagManager.asset
Labels: task

#124 Bug/#111 on application quit check enemy destroy
  src/Assets/LightSkyDefense/Prefabs/Enemy.prefab.meta
  src/Assets/LightSkyDefense/Scripts/Enemies/EnemyDestroyDispatcher.cs
  src/Assets/LightSkyDefense/Scripts/TowerWinBehaviour.cs.meta
Labels: bug

#122 Bug/#113 make gameover screen not stuck to your camera
  src/Assets/LightSkyDefense/Scripts/GameManager.cs
Labels: bug

#128 Feature/#126 create git hooks
  hooks/commit-msg
  hooks/pre-push
  init.sh
Labels: task

#125 Bug/#117 pathfollower fixes
  src/Assets/LightSkyDefense/Scripts/Enemies/Enemy.cs
  src/Assets/LightSkyDefense/Scripts/Enemies/PathFollower.cs
  src/Assets/LightSkyDefense/Scripts/GameStates/Waves.cs
  src/Assets/LightSkyDefense/Scripts/Path/Path.cs
  src/Assets/SteamVR/InteractionSystem/Samples/BuggyBuddy/Materials/LightCone_Blue.mat
Labels: bug

#130 Feature/#129 update enemy destroy behaviour
  src/Assets/LightSkyDefense/Resources/Prefabs/Enemy.prefab
  src/Assets/LightSkyDefense/Scripts/Enemies/Enemy.cs
Labels: bug

#134 Add shotgun model #132
  artwork/models/shotgun/shotgun.blend
  artwork/models/shotgun/shotgun.fbx
  src/Assets/LightSkyDefense/Models/Shotgun/ShotgunBodyMat.mat
  src/Assets/LightSkyDefense/Models/Shotgun/ShotgunBodyMat.mat.meta
  src/Assets/LightSkyDefense/Models/Shotgun/ShotgunGunMat.mat
  src/Assets/LightSkyDefense/Models/Shotgun/ShotgunGunMat.mat.meta
  src/Assets/LightSkyDefense/Models/Shotgun/shotgun.fbx
  src/Assets/LightSkyDefense/Models/Shotgun/shotgun.fbx.meta
  src/Assets/LightSkyDefense/Models/shotgun.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ChildShotgun.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ChildShotgun.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ParentShotgun.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ParentShotgun.prefab.meta
Labels: feature

#138 Feature/#137 add dial for fallback
  src/Assets/LightSkyDefense/Resources/Fonts/Anonymous_Pro.ttf
  src/Assets/LightSkyDefense/Resources/Fonts/Anonymous_Pro.ttf.meta
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/Dial.cs
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/SpawnDialOption.cs
  src/Assets/LightSkyDefense/Scripts/Controls/FallbackController.cs
  src/Assets/LightSkyDefense/Scripts/Controls/FallbackController.cs.meta
Labels: feature

#131 Feature/#119 update tower setup
  hooks/commit-msg
  src/Assets/LightSkyDefense/Prefabs/Enemy.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncher.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Turret/Bullet.prefab
  src/Assets/LightSkyDefense/Resources/Prefabs/Enemy.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours.meta
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/Damageable.cs
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/Damageable.cs.meta
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/PlacementCost.cs
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/PlacementCost.cs.meta
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/SpawnCreditOnDie.cs
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/SpawnCreditOnDie.cs.meta
  src/Assets/LightSkyDefense/Scripts/Common/Events/OnGameEndTarget.cs
  src/Assets/LightSkyDefense/Scripts/Common/GameOver/GameOver.cs
  src/Assets/LightSkyDefense/Scripts/Enemies/Enemy.cs
  src/Assets/LightSkyDefense/Scripts/Enemies/EnemyDestroyDispatcher.cs
  src/Assets/LightSkyDefense/Scripts/GameManager.cs
  src/Assets/LightSkyDefense/Scripts/Pickups/Credit.cs
  src/Assets/LightSkyDefense/Scripts/Pickups/SpawnCreditOnDestruction.cs
  src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs
  src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/BulletBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Towers/MissileLauncher.cs
  src/Assets/LightSkyDefense/Scripts/Towers/MissileLauncher.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/Projectiles.meta
  src/Assets/LightSkyDefense/Scripts/Towers/Projectiles/BulletBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Towers/Projectiles/BulletBehaviour.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/States.meta
  src/Assets/LightSkyDefense/Scripts/Towers/States/CelebrationState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/CelebrationState.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/States/IdleRotationState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/IdleRotationState.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/States/PredictTargetPositionState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/PredictTargetPositionState.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/States/TowerState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/TowerState.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/TowerBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Towers/TowerCelebrationBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Towers/Turret.cs
  src/Assets/LightSkyDefense/Scripts/Towers/Turret.cs.meta
  src/Assets/LightSkyDefense/Scripts/UI/PlayerStatistics.cs
  src/Assets/LightSkyDefense/Scripts/UI/Scoreboard.cs
Labels: task

#145 Feature/#142 tower range preview effect
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncherDialOptionPreview.prefab
  src/Assets/LightSkyDefense/Resources/Materials.meta
  src/Assets/LightSkyDefense/Resources/Materials/ColliderRenderMat.mat
  src/Assets/LightSkyDefense/Resources/Materials/ColliderRenderMat.mat.meta
  src/Assets/LightSkyDefense/Resources/Shaders/IntersectShader.shader
  src/Assets/LightSkyDefense/Resources/Shaders/IntersectShader.shader.meta
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Common/Effects/RenderableColliders.cs
  src/Assets/LightSkyDefense/Scripts/Common/Effects/RenderableColliders.cs.meta
  src/Assets/LightSkyDefense/Scripts/GameManager.cs
Labels: feature

#149 Feature/#119 add missile behaviour
  src/Assets/LightSkyDefense/Prefabs/Scoreboard.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/Missile.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncher.prefab
  src/Assets/LightSkyDefense/Resources/Prefabs/Enemy.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Common/SteeringBehaviours/Aggregates/ScoreboardSteeringBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Common/SteeringBehaviours/Utils/Seek.cs
  src/Assets/LightSkyDefense/Scripts/Data.meta
  src/Assets/LightSkyDefense/Scripts/Data/LayerMasks.cs
  src/Assets/LightSkyDefense/Scripts/Data/LayerMasks.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs
  src/Assets/LightSkyDefense/Scripts/Towers/MissileLauncher.cs
  src/Assets/LightSkyDefense/Scripts/Towers/Projectiles/MissileBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Towers/Projectiles/MissileBehaviour.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/States/IdleRotationState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/ShootBulletState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/ShootBulletState.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/States/ShootMissileState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/ShootMissileState.cs.meta
  src/ProjectSettings/DynamicsManager.asset
Labels: feature

#155 Update target detection #119
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/Missile.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncher.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ParentShotgun.prefab
  src/Assets/LightSkyDefense/Scripts/Data/Layers.cs
  src/Assets/LightSkyDefense/Scripts/Data/Layers.cs.meta
  src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs
  src/Assets/LightSkyDefense/Scripts/Towers/Projectiles/MissileBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/CelebrationState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/IdleRotationState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/ShootMissileState.cs
Labels: task

#158 Feature/#119 update enemy knockback rotation
  src/Assets/LightSkyDefense/Resources/Prefabs/Enemy.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Common/SteeringBehaviours/Aggregates/EnemySteeringBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Common/SteeringBehaviours/Aggregates/ScoreboardSteeringBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Enemies/Enemy.cs
  src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/TowerState.cs
Labels: bug

#163 Feature/#119 missile launcher look direction
  artwork/models/missile_launcher/missile_launcher.blend
  artwork/models/missile_launcher/missile_launcher.fbx
  src/Assets/LightSkyDefense/Controls/Dial.meta
  src/Assets/LightSkyDefense/GameStates.meta
  src/Assets/LightSkyDefense/Models/Credit.meta
  src/Assets/LightSkyDefense/Models/Credit/Credit.fbx
  src/Assets/LightSkyDefense/Models/Credit/Credit.fbx.meta
  src/Assets/LightSkyDefense/Models/Missile.meta
  src/Assets/LightSkyDefense/Models/Missile/Missile.fbx
  src/Assets/LightSkyDefense/Models/Missile/Missile.fbx.meta
  src/Assets/LightSkyDefense/Models/MissileLauncher/missile_launcher.fbx
  src/Assets/LightSkyDefense/Models/MissileLauncher/missile_launcher.fbx.meta
  src/Assets/LightSkyDefense/Models/Scoreboard.meta
  src/Assets/LightSkyDefense/Models/Scoreboard/Scoreboard.fbx
  src/Assets/LightSkyDefense/Models/Scoreboard/Scoreboard.fbx.meta
  src/Assets/LightSkyDefense/Models/Scoreboard/newScoreboard.fbx
  src/Assets/LightSkyDefense/Models/Scoreboard/newScoreboard.fbx.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/Missile.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncher.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncherDialOption.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncherDialOptionPreview.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ChildShotgun.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ChildShotgun.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ParentShotgun.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/Shotgun.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/Shotgun.prefab.meta
  src/Assets/LightSkyDefense/Resources/Prefabs/Enemy.prefab
  src/Assets/LightSkyDefense/Scripts/SteeringBehaviours/Combinatorics.meta
  src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs
  src/Assets/LightSkyDefense/Scripts/Towers/Projectiles/MissileBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/CelebrationState.cs
  src/Assets/LightSkyDefense/Scripts/Towers/States/ShootMissileState.cs
  src/Assets/LightSkyDefense/Util.meta
Labels: feature

#161 Feature/#160 credit rotation
  .gitignore
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/SpawnCreditOnDie.cs
  src/Assets/LightSkyDefense/Scripts/Pickups/Credit.cs
Labels: feature

#172 IntersectShader fades when close to camera #169
  src/Assets/LightSkyDefense/Resources/Shaders/IntersectShader.shader
Labels: feature

#177 Fix in enemy artwork and prefab #167
  artwork/models/enemy/Enemy.blend
  artwork/models/enemy/Enemy.fbx
  src/Assets/LightSkyDefense/Models/Enemy/Enemy.fbx
  src/Assets/LightSkyDefense/Models/Enemy/Enemy.fbx.meta
Labels: bug

#176 Feature/#166 win text on game win
  src/Assets/LightSkyDefense/Resources/Text.meta
  src/Assets/LightSkyDefense/Resources/Text/GameOverText.prefab
  src/Assets/LightSkyDefense/Resources/Text/GameOverText.prefab.meta
  src/Assets/LightSkyDefense/Resources/Text/GameWinText.prefab
  src/Assets/LightSkyDefense/Resources/Text/GameWinText.prefab.meta
  src/Assets/LightSkyDefense/Scripts/Controls/PauseMenu/PauseMenuBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/GameStates/LoseState.cs
  src/Assets/LightSkyDefense/Scripts/GameStates/WinState.cs
Labels: feature, good first issue

#180 Add build collision check script to spawn dial #82
  src/Assets/LightSkyDefense/Controls.meta
  src/Assets/LightSkyDefense/Prefabs/Player.prefab
  src/Assets/LightSkyDefense/Prefabs/Player.prefab.meta
  src/Assets/LightSkyDefense/Prefabs/Towers/MachineGun/MachineGun.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MachineGun/MachineGunDialOption.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MachineGun/MachineGunDialOptionPreview.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncher.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncherDialOption.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncherDialOptionPreview.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/Shotgun.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ShotgunDialOption.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ShotgunDialOptionPreview.prefab
  src/Assets/LightSkyDefense/Resources/Prefabs/PathWayPoint.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/Buildable.cs
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/Buildable.cs.meta
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/SpawnDialOption.cs
  src/Assets/LightSkyDefense/Scripts/Controls/FallbackController.cs
Labels: feature, high priority

#181 Feature/#173 fix deletable
  src/Assets/LightSkyDefense/Prefabs/Player.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MachineGun/MachineGun.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncher.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/Shotgun.prefab
  src/Assets/LightSkyDefense/Scripts/Controls/Deletable.cs
  src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs
  src/Assets/SteamVR/InteractionSystem/Core/Prefabs/LeftRenderModel Slim.prefab
  src/Assets/SteamVR/InteractionSystem/Core/Prefabs/RightRenderModel Slim.prefab
  src/bindings_vive_controller.json
Labels: bug, feature, high priority

#184 Feature/#170 show tower prices on dial
  src/Assets/LightSkyDefense/Prefabs/Towers/MachineGun/MachineGunDialOption.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncherDialOption.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/ShotgunDialOption.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/CurrentCreditsDisplay.cs
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/CurrentCreditsDisplay.cs.meta
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/CurrentCreditsText.prefab
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/CurrentCreditsText.prefab.meta
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/DialCostText.prefab
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/DialCostText.prefab.meta
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/DialOption.cs
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/SpawnDialOption.cs
Labels: low priority

#187 Bug/#186 Textmesh is visible through all objects
  src/Assets/LightSkyDefense/Resources/Text/GameOverText.prefab
  src/Assets/LightSkyDefense/Resources/Text/GameWinText.prefab
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/CurrentCreditsText.prefab
  src/Assets/LightSkyDefense/Scripts/Controls/Dial/DialCostText.prefab
Labels: bug
