Repository vr-tower-defense/vr-tower-defense, pull requests merged in 2019-06, with the labels that each got.

#194 Feature/#193 update total wave count
  src/Assets/LightSkyDefense/Controls/Dial.meta
  src/Assets/LightSkyDefense/Prefabs/Enemies/BaseEnemy.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Common/Behaviours/Buildable.cs
  src/Assets/LightSkyDefense/Scripts/Common/Steering/Behaviours/Flocking.cs
  src/Assets/LightSkyDefense/Scripts/Common/Steering/RigidbodySteering.cs
  src/Assets/LightSkyDefense/Scripts/GameStates/InfinityState.cs
  src/Assets/LightSkyDefense/Scripts/SteeringBehaviours.meta
  src/Assets/LightSkyDefense/Scripts/SteeringBehaviours/Aggregates.meta
  src/Assets/LightSkyDefense/Scripts/SteeringBehaviours/Combinatorics.meta
  src/Assets/LightSkyDefense/Scripts/SteeringBehaviours/Utils.meta
  src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs
  src/Assets/LightSkyDefense/Scripts/Towers/Projectiles/MissileBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/UI/Scoreboard.cs
  src/Assets/LightSkyDefense/Waves/WaveSteps/SpawnBossOne.asset
  src/Assets/LightSkyDefense/Waves/WaveSteps/SpawnBossTwo.asset
  src/Assets/LightSkyDefense/Waves/WaveSteps/SpawnBossTwo.asset.meta
  src/Assets/LightSkyDefense/Waves/WaveSteps/SpawnEnemy.asset
  src/Assets/LightSkyDefense/Waves/WaveSteps/SpawnJammerEnemy.asset
  src/Assets/LightSkyDefense/Waves/WaveSteps/SpawnShooter.asset
  src/Assets/LightSkyDefense/Waves/WaveSteps/SpawnSplitter.asset
Labels: bug

#201 Disable states by default in towers #200
  src/Assets/LightSkyDefense/Prefabs/Towers/MachineGun/MachineGun.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/MissileLauncher/MissileLauncher.prefab
  src/Assets/LightSkyDefense/Prefabs/Towers/Shotgun/Shotgun.prefab
Labels: bug

#196 Feature/#195 update path colliders
  src/Assets/LightSkyDefense/Prefabs/Path/Path.prefab
  src/Assets/LightSkyDefense/Prefabs/Player.prefab
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Common/Steering/EnemyFlocking.asset
  src/Assets/LightSkyDefense/Scripts/Controls/PauseMenu/PauseMenu.prefab
  src/Assets/LightSkyDefense/Scripts/Controls/PauseMenu/PauseMenu.prefab.meta
  src/Assets/LightSkyDefense/Scripts/Controls/PauseMenu/PauseMenuBehaviour.cs
  src/Assets/LightSkyDefense/Scripts/Path/Path.cs
Labels: low priority

#221 Make sure scoreboard lives doesn't drop below 0 #216
  src/Assets/LightSkyDefense/Scripts/UI/Scoreboard.cs
Labels: bug

#222 Reset jam timer when hit by jam bullet #216
  src/Assets/LightSkyDefense/Scripts/Towers/States/JamState.cs
Labels: bug

#224 Bugzoooka was not properly pushed #116
  src/Assets/LightSkyDefense/Prefabs/Enemies/BugzookaEnemy.prefab
  src/Assets/LightSkyDefense/Prefabs/Enemies/Projectiles/BugzookaProjectile.prefab
Labels: bug

#230 Add comments to intersect shader #229
  src/Assets/LightSkyDefense/Resources/Shotgun.meta
  src/Assets/LightSkyDefense/Scenes/LSDScene.unity
  src/Assets/LightSkyDefense/Scripts/Towers/States/ShootBulletState.cs
  src/Assets/LightSkyDefense/Shaders/IntersectShader.shader
  src/Assets/LightSkyDefense/Waves/Wave 7.asset
  src/Assets/LightSkyDefense/Waves/Wave 9.asset
Labels: task
